# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a82a4edd0d7323b80a4344a3c12f3df3c1d292f64cc319f405f14cb0d5b3182732b7c6948649d1df71c320836e2c52f1ecbd4b4f519e117679ab1df73e55a494

test:
  secret_key_base: 5073bfe718bdb93179bc247f755210be5d3f86cf8c9d44ccbf246246cf07bb5071820436953ddb698e07df1b73f62807594ae9b1c79a753ec282257064323b71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
